create table batch_run (
    batch_id number generated by default as identity primary key,
    batch_name varchar2(100) not null,
    status varchar2(20) not null,
    started_at timestamp default systimestamp not null,
    finished_at timestamp,
    rows_read number default 0 not null,
    rows_inserted number default 0 not null,
    rows_updated number default 0 not null,
    rows_rejected number default 0 not null,
    constraint ck_batch_status check(status in ('RUNNING','SUCCESS','PARTIAL','FAILED'))
);

create table job_run (
    job_run_id number generated by default as identity primary key,
    batch_id number not null references batch_run(batch_id),
    job_name varchar2(100) not null,
    status varchar2(20) not null,
    started_at timestamp default systimestamp not null,
    finished_at timestamp,
    rows_read number default 0 not null,
    rows_inserted number default 0 not null,
    rows_updated number default 0 not null,
    rows_rejected number default 0 not null,
    constraint ck_job_status check(status in ('RUNNING','SUCCESS','PARTIAL','FAILED'))
);

create table error_log (
    error_id number generated by default as identity primary key,
    batch_id number,
    job_run_id number,
    module_name varchar2(200),
    error_code number,
    error_message varchar2(4000),
    backtrace varchar2(4000),
    created_at timestamp default systimestamp not null
);

create table rejected_row (
    reject_id number generated by default as identity primary key,
    batch_id number,
    job_run_id number,
    entity_name varchar2(50),
    source_key varchar2(200),
    reject_reason varchar2(2000),
    payload clob,
    created_at timestamp default systimestamp not null
);

create table dq_rule (
    rule_id number generated by default as identity primary key,
    rule_code varchar2(100) not null unique,
    entity_name varchar2(50) not null,
    target_table varchar2(128) not null,
    key_expression varchar2(500) not null,
    failure_condition varchar2(2000) not null,
    severity varchar2(20) not null,
    enabled_flag char(1) default 'Y' not null,
    constraint ck_dq_severity check(severity in ('INFO','WARNING','ERROR','CRITICAL')),
    constraint ck_dq_enabled check(enabled_flag in ('Y','N'))
);

create table dq_execution (
    execution_id number generated by default as identity primary key,
    batch_id number,
    entity_name varchar2(50) not null,
    status varchar2(20) not null,
    started_at timestamp default systimestamp not null,
    finished_at timestamp,
    rules_executed number default 0 not null,
    violations_found number default 0 not null,
    dq_score number(7,2),
    constraint ck_dq_exec_status check(status in ('RUNNING','COMPLETED','FAILED'))
);

create table dq_violation (
    violation_id number generated by default as identity primary key,
    execution_id number not null references dq_execution(execution_id),
    rule_id number not null references dq_rule(rule_id),
    business_key varchar2(1000),
    severity varchar2(20),
    violation_message varchar2(2000),
    detected_at timestamp default systimestamp not null
);

create table recon_run (
    recon_run_id number generated by default as identity primary key,
    batch_id number,
    status varchar2(20) not null,
    started_at timestamp default systimestamp not null,
    finished_at timestamp,
    total_count number default 0 not null,
    matched_count number default 0 not null,
    mismatch_count number default 0 not null,
    constraint ck_recon_status check(status in ('RUNNING','COMPLETED','FAILED'))
);

create table recon_result (
    recon_result_id number generated by default as identity primary key,
    recon_run_id number not null references recon_run(recon_run_id),
    transaction_ref varchar2(100) not null,
    result_status varchar2(30) not null,
    source_count number default 0 not null,
    dwh_count number default 0 not null,
    source_amount number(18,2),
    dwh_amount number(18,2),
    amount_difference number(18,2),
    details varchar2(2000),
    created_at timestamp default systimestamp not null,
    constraint ck_recon_result check(
        result_status in ('MATCHED','MISSING_DWH','AMOUNT_MISMATCH','DUPLICATE_SOURCE','DUPLICATE_DWH')
    )
);
