create table dim_customer (
    customer_sk number generated by default as identity primary key,
    customer_id number not null,
    customer_name varchar2(200) not null,
    customer_segment varchar2(30),
    status_code varchar2(20),
    country_code varchar2(2),
    valid_from date not null,
    valid_to date,
    is_current char(1) not null,
    constraint ck_dim_customer_current check(is_current in ('Y','N'))
);

create table dim_account (
    account_sk number generated by default as identity primary key,
    account_id number not null unique,
    account_number varchar2(34) not null,
    customer_id number not null,
    product_code varchar2(30),
    currency_code varchar2(3),
    status_code varchar2(20),
    opened_date date
);

create table dim_product (
    product_sk number generated by default as identity primary key,
    product_code varchar2(30) not null unique,
    product_name varchar2(100) not null,
    product_group varchar2(50) not null
);

create table dim_date (
    date_sk number primary key,
    calendar_date date not null unique,
    calendar_day number not null,
    calendar_month varchar2(7) not null,
    calendar_year number not null,
    month_name varchar2(20),
    quarter_no number
);
