create table fact_transaction (
    transaction_sk number generated by default as identity primary key,
    transaction_ref varchar2(100) not null unique,
    customer_sk number not null references dim_customer(customer_sk),
    account_sk number not null references dim_account(account_sk),
    product_sk number not null references dim_product(product_sk),
    date_sk number not null references dim_date(date_sk),
    transaction_type varchar2(20) not null,
    amount number(18,2) not null,
    signed_amount number(18,2) not null,
    fee_amount number(18,2) default 0 not null,
    currency_code varchar2(3) not null,
    loaded_at timestamp default systimestamp not null
);

create table fact_account_balance (
    balance_sk number generated by default as identity primary key,
    account_sk number not null references dim_account(account_sk),
    date_sk number not null references dim_date(date_sk),
    balance_amount number(18,2) not null,
    currency_code varchar2(3) not null,
    loaded_at timestamp default systimestamp not null,
    constraint uq_account_balance unique(account_sk,date_sk)
);
